### ISSUE TITLE
Can you please provide a release?

### ISSUE THREAD

**Issue by penderes** [mnaiman/RainmeterPluginNetAtmo#1]
Hi @mnaiman,

loving your plugin. I still have the old version that was available on BitBucket. Everytime the Netatmo API is under maintenance, the plugin crashes my whole RM instance.

However I saw that you improved error handling a few months ago and I'm hoping this fixes it.

Unfortunately I don't have any environment set up to build the plugin myself. Would it be possible for you to provide the updated .dll under releases on Github as well like you did on BitBucket?

Thanks in advance and cheers!

**Comment by mnaiman** [comment]
Added release binary for x64.
Updated readme:
Prerequisites
    .NET Framework minimum 4.6.2 - https://dotnet.microsoft.com/download/dotnet-framework
    You need to install correct version of dll x64 for 64bit Rainmeter and x86 for 32bit

**Comment by mnaiman** [comment]
BTW: these fixes were for crashing you're describing, so report if it keeps happening.
